// Render only the shared model. Agent text never becomes HTML markup.
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
const md = value => String(value ?? "").replace(/[\x00-\x1f\x7f]/g, " ").replace(/[\`*_{}\[\]()<>#+.!|&]/g, c => String.fromCharCode(92) + c);
const mdBlock = value => String(value ?? "").split(/\r?\n/).map(md).join("\n");
const evidenceArtifacts = task => task.artifacts.filter(record => ["report", "proof"].includes(record.data.type) && record.content?.verified && typeof record.content.text === "string");
const mark = status => ({ done: "✓", failed: "✗", running: "…", pending: "○", unknown: "?" }[status] ?? "?");
const route = task => `/task/${Buffer.from(task.key).toString("base64url")}`;
function safeUrl(value) {
  try { const url = new URL(value); return url.protocol === "https:" && !url.username && !url.password ? url.href : null; }
  catch { return null; }
}
function prUrl(task) {
  const repository = safeUrl(task.prEvidence?.data.repository);
  return repository && /^[1-9]\d*$/.test(task.pr) ? `${repository.replace(/\/$/, "")}/pull/${task.pr}` : null;
}
function link(label, value) { const url = safeUrl(value); return url ? `<a href="${esc(url)}" rel="noopener noreferrer">${esc(label)}</a>` : esc(label); }
function cyclesHtml(task) {
  return task.cycles.map(cycle => `<p class="cycle">Cycle ${cycle.number} of ${task.requiredCycles}${cycle.steps.map(step => `<span class="step ${esc(step.status)}">${mark(step.status)} ${esc(step.role)}</span>`).join(" ")}</p>`).join("");
}
function projectColor(key) {
  let hash = 0; for (const char of key) hash = (hash * 31 + char.codePointAt(0)) >>> 0;
  return `project-${hash % 5}`;
}
const columnMark = key => ({ backlog: "📋", design: "🎨", building: "🔨", review: "🔁", ready: "✅", done: "🏁" }[key]);
function metadata(task) {
  return `<p class="muted">${esc(task.sourceLabel)} · <span class="dot ${projectColor(task.project)}" aria-hidden="true"></span>${esc(task.projectName)} · ${esc(task.size)}${task.risk ? ` · risk: ${esc(task.risk)}` : ""}</p><p>${task.pr ? link(`PR ${task.pr}`, prUrl(task)) : "No PR recorded"} · head ${esc(task.currentHead?.slice(0, 7) ?? "unknown")} · repair round ${esc(task.round)}</p>`;
}
function runTime(run) {
  const start = Date.parse(run.started), end = Date.parse(run.ended);
  return Number.isFinite(start) && Number.isFinite(end) && end >= start ? `${Math.floor((end - start) / 1000)} s · ${run.started} to ${run.ended}` : run.started ? `${run.started} · duration unknown` : "time unknown";
}
function details(task) {
  const sections = [
    ["Loop", `<p>${task.loop.steps.map(step => `<span class="step ${esc(step.status)}">${esc(step.label)}</span>`).join(" ")}</p><p>${esc(task.loop.explanation)}</p><p>${esc(task.state)} · repair round ${esc(task.round)}</p>${cyclesHtml(task)}<p>Current head: ${esc(task.currentHead ?? "unknown")}</p>`],
    ["Brief", task.brief ? `<p>Goal: ${esc(task.briefFields.goal ?? "not recorded")}</p><p>Acceptance:</p><pre>${esc(task.briefFields.acceptance ?? "not recorded")}</pre><details><summary>Full brief</summary><pre>${esc(task.brief)}</pre></details>` : "<p>No verified brief content is available.</p>"],
    ["Agent runs", task.runs.length ? `<ul>${task.runs.map(run => `<li>${esc(run.id)} · ${esc(run.evidence?.data.provider ?? "provider unknown")} · ${esc(run.role)} · ${esc(run.status)} · ${esc(runTime(run))} · tokens ${esc(run.tokens || "unknown")}</li>`).join("")}</ul>` : "<p>No runs recorded.</p>"],
    ["Evidence", (task.ledger.length ? `<ul>${task.ledger.map(row => `<li>${esc(row.kind)} · cycle ${esc(row.cycle)} · head ${esc(row.sha)} · ${esc(row.run)} · ${esc(row.at)}</li>`).join("")}</ul>` : "<p>No verdicts recorded.</p>") + evidenceArtifacts(task).map(record => `<h4>${esc(record.data.label)}</h4><p>${esc(record.source)} · ${esc(record.observedAt)} · digest verified</p><pre>${esc(record.content.text)}</pre>`).join("")],
    ["Findings", task.findings.length ? `<ul>${task.findings.map(row => `<li>${esc(row.severity)} · ${esc(row.summary)} · ${esc(row.status)}${row.reason ? ` · ${esc(row.reason)}` : ""}</li>`).join("")}</ul>` : "<p>No findings recorded.</p>"],
    ["Artifacts", task.artifacts.length ? `<ul>${task.artifacts.map(record => `<li>${link(record.data.label, record.data.url)}${record.data.path ? record.content?.verified ? " · digest verified" : " · content not verified" : ""} · ${esc(record.source)} · ${esc(record.observedAt)}${record.content?.kind === "image" && /^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(record.content.dataUrl) ? `<figure><img src="${record.content.dataUrl}" alt="${esc(record.data.label)}"><figcaption>${esc(record.data.label)} · digest verified</figcaption></figure>` : ""}</li>`).join("")}</ul>` : "<p>No artifacts recorded.</p>"],
    ["Latest decisions", task.decisions.length ? `<ul>${task.decisions.map(row => `<li>${esc(row.at)} · ${esc(row.decision)} · ${esc(row.why)}</li>`).join("")}</ul>` : "<p>No decisions recorded.</p>"],
  ];
  return sections.map(([title, html]) => `<section><h3>${title}</h3>${html}</section>`).join("");
}
const CSS = `:root{color-scheme:dark}*{box-sizing:border-box}body{--bg:#121212;--panel:#1b1b1b;--text:#f0f0f0;--muted:#b8b8b8;--line:#858585;--accent:#b8b5ff;--need:#ff997a;--ok:#7be2a0;margin:0;background:var(--bg);color:var(--text);font:14px/1.5 system-ui,sans-serif}body:has(#light:checked){color-scheme:light;--bg:#fafafa;--panel:#fff;--text:#171717;--muted:#525252;--line:#737373;--accent:#4338ca;--need:#9a3412;--ok:#166534}a{color:var(--accent)}a:focus-visible,button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid var(--accent);outline-offset:3px}header{padding:18px 20px;border-bottom:1px solid var(--line)}h1{font-size:22px;margin:0 0 8px}h2{font-size:16px}h3{font-size:15px}.summary,.filters{display:flex;flex-wrap:wrap;gap:12px;margin:10px 0}.filters button{font:inherit;color:var(--text);background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:5px 12px}.filters button[aria-pressed=true]{border:2px solid var(--accent)}.board{display:grid;grid-template-columns:repeat(6,minmax(240px,1fr));gap:12px;padding:20px;overflow-x:auto}.column{min-width:0}.card,.detail{background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:12px;margin-bottom:12px}.card.needs{border:2px solid var(--need)}.needs-reason,.failed{color:var(--need)}.done{color:var(--ok)}.current{color:var(--accent);font-weight:bold}.needs-owner{color:var(--need);font-weight:bold}.skipped{text-decoration:line-through;color:var(--muted)}.muted{color:var(--muted)}.step{display:inline-block;border:1px solid var(--line);border-radius:4px;padding:1px 4px;margin:3px}.cycle{font-size:12px}.detail{max-width:900px;margin:20px auto}.detail section{border-top:1px solid var(--line)}img{max-width:100%;height:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere}p,li{overflow-wrap:anywhere}.diagnostics{padding:0 20px}.dot{display:inline-block;width:8px;height:8px;background:var(--accent);border-radius:50%;margin-right:5px}.project-0{background:#b8b5ff}.project-1{background:#4cc7bd}.project-2{background:#f0a35a}.project-3{background:#ff99c8}.project-4{background:#7be2a0}[hidden]{display:none!important}@media(max-width:700px){.board{display:flex;flex-direction:column;overflow:visible;padding:14px}.column.attention{order:-1}.column.empty{display:none}.detail{margin:14px}.filters{gap:6px}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}`;
export const BOARD_ENHANCEMENT = `let project='',needs=false;function filter(){const buttons=[...document.querySelectorAll('[data-filter]')];if(project&&!buttons.some(b=>b.dataset.filter===project))project='';buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter==='needs'?needs:b.dataset.filter===project)));document.querySelectorAll('.card').forEach(card=>{card.hidden=!!(project&&card.dataset.project!==project||needs&&card.dataset.needs!=='true')});document.querySelectorAll('.column').forEach(col=>{const visible=[...col.querySelectorAll('.card')].filter(card=>!card.hidden);col.classList.toggle('empty',!visible.length);col.classList.toggle('attention',visible.some(card=>card.dataset.needs==='true'))})}document.addEventListener('click',event=>{const button=event.target.closest('[data-filter]');if(!button)return;if(button.dataset.filter==='needs')needs=!needs;else project=button.dataset.filter;filter()});document.addEventListener('click',event=>{const anchor=event.target.closest('a[href^="#detail-"]');if(!anchor)return;const detail=document.getElementById(anchor.getAttribute('href').slice(1));if(detail)detail.open=true});`;

function liveScript(taskKey) {
  const stream = taskKey ? `/?events=1&task=${Buffer.from(taskKey).toString("base64url")}` : "/?events=1";
  return `const stream=new EventSource(${JSON.stringify(stream)});const state=document.getElementById('live-state');stream.addEventListener('board',event=>{try{const payload=JSON.parse(event.data);const page=new DOMParser().parseFromString(payload.html,'text/html');const content=page.getElementById('board-content');const summary=page.getElementById('board-summary');if(!content||!summary)throw new Error('incomplete update');document.getElementById('board-content').replaceChildren(...content.childNodes);document.getElementById('board-summary').replaceChildren(...summary.childNodes);const filters=page.getElementById('board-filters');const oldFilters=document.getElementById('board-filters');if(filters&&oldFilters)oldFilters.replaceChildren(...filters.childNodes);filter();state.textContent=payload.stale?'Update failed; showing the last valid snapshot.':'Live updates connected.'}catch{state.textContent='Update failed; showing the last valid snapshot.'}});stream.onerror=()=>{state.textContent='Connection lost; showing the last snapshot. Reconnecting.'};`;
}

export function renderBoardHtml(model, { taskKey = null, snapshot = true, live = false } = {}) {
  const task = taskKey ? model.tasks.find(task => task.key === taskKey) : null;
  if (taskKey && !task) throw new RangeError("unknown task key");
  const counts = model.counts;
  const filters = `<div class="filters" id="board-filters"><button data-filter="needs" aria-pressed="false">Needs you (${counts.needsOwner})</button><button data-filter="" aria-pressed="true">All projects</button>${[...new Map(model.tasks.map(task => [task.project, task.projectName])).entries()].map(([key,name]) => `<button data-filter="${esc(key)}" aria-pressed="false">${esc(name)}</button>`).join("")}</div>`;
  const cardHtml = task => `<article class="card${task.reasons.length ? " needs" : ""}" data-project="${esc(task.project)}" data-needs="${!!task.reasons.length}"><h3><a href="${snapshot ? `#detail-${Buffer.from(task.key).toString("base64url")}` : route(task)}">${esc(task.id)} · ${esc(task.title)}</a></h3>${metadata(task)}${task.reasons.map(reason => `<p class="needs-reason">🔴 ${esc(reason.text)}${reason.recommendation ? ` · Recommended: ${esc(reason.recommendation)}` : ""}</p>`).join("")}<p>${task.agents.map(agent => `<span class="dot" aria-hidden="true"></span>${esc(agent.provider ?? "provider unknown")} · ${esc(agent.role)} · recorded running`).join("<br>")}${task.inferredWork ? "Inferred from the open PR; no recorded running agent" : ""}</p>${cyclesHtml(task)}</article>`;
  const body = task ? `<main class="detail"><a href="/">Board</a><h2>${esc(task.id)} · ${esc(task.title)}</h2>${metadata(task)}${details(task)}</main>` : `<main class="board">${model.columns.map(column => `<section class="column${column.needsOwner ? " attention" : ""}${column.tasks.length ? "" : " empty"}"><h2>${esc(column.name)} (${column.tasks.length})</h2>${column.tasks.map(cardHtml).join("") || "<p class=muted>No tasks.</p>"}</section>`).join("")}</main>${snapshot ? model.tasks.map(task => `<details class="detail" id="detail-${Buffer.from(task.key).toString("base64url")}"><summary>${esc(task.id)} · ${esc(task.sourceLabel)} · ${esc(task.title)}</summary>${details(task)}</details>`).join("") : ""}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sage task board</title><style>${CSS}</style></head><body><header><h1>Sage task board</h1><p>${snapshot ? "Offline snapshot" : "Recorded board"} · ${esc(model.at)}</p><label><input id="light" type="checkbox"> Light theme</label><p class="summary" id="board-summary">${counts.needsOwner} need you · ${counts.recordedAgents} recorded agents · ${counts.inferredWork} inferred PRs · ${counts.inReview} in review</p>${task ? "" : filters}${live ? "<p id=live-state role=status>Connecting to live updates; showing the recorded snapshot.</p>" : ""}</header><div id="board-content">${model.diagnostics.length ? `<aside class="diagnostics"><h2>Incomplete sources</h2>${model.diagnostics.map(d => `<p>${esc(d.source)} · ${esc(d.project ?? "")} · ${esc(d.message)}</p>`).join("")}</aside>` : ""}${body}</div><script>${BOARD_ENHANCEMENT}${live ? liveScript(taskKey) : ""}</script></body></html>`;
}

export function renderTaskText(task) {
  return `**${md(task.id)} ${md(task.title)}**\n${md(task.sourceLabel)} · ${md(task.projectName)} · ${md(task.state)} · ${md(task.size)}${task.risk ? ` · risk: ${md(task.risk)}` : ""}\n\n**Loop**\n${task.loop.steps.map(step => `${step.status === "done" ? "✓ " : step.status === "current" ? "▶ " : step.status === "needs-owner" ? "🔴 " : ""}${step.status === "skipped" ? `~~${md(step.label)}~~` : md(step.label)}`).join(" · ")}\n> ${md(task.loop.explanation)}\n${md(task.state)} · repair round ${md(task.round)} · head ${md(task.currentHead ?? "unknown")}\n${task.cycles.map(c => `Cycle ${c.number} of ${task.requiredCycles}: ${c.steps.map(s => `${mark(s.status)} ${s.role}`).join(" · ")}`).join("\n")}\n\n**Brief**\nGoal: ${mdBlock(task.briefFields.goal ?? "not recorded")}\nAcceptance: ${mdBlock(task.briefFields.acceptance ?? "not recorded")}\n\nFull brief:\n${mdBlock(task.brief ?? "No verified brief content is available.")}\n\n**Agent runs**\n${task.runs.map(r => `${md(r.id)} ${md(r.evidence?.data.provider ?? "provider unknown")} · ${md(r.role)} · ${md(r.status)} · ${md(runTime(r))} · tokens ${md(r.tokens || "unknown")}`).join("\n") || "No runs recorded."}\n\n**Evidence**\n${task.ledger.map(r => `${md(r.kind)} · cycle ${md(r.cycle)} · ${md(r.sha)} · ${md(r.run)} · ${md(r.at)}`).join("\n") || "No verdicts recorded."}${evidenceArtifacts(task).map(r => `\n\n${md(r.data.label)} · ${md(r.source)} · ${md(r.observedAt)} · digest verified\n${mdBlock(r.content.text)}`).join("")}\n\n**Findings**\n${task.findings.map(r => `${md(r.severity)} · ${md(r.summary)} · ${md(r.status)} · ${md(r.reason)}`).join("\n") || "No findings recorded."}\n\n**Artifacts**\n${task.artifacts.map(r => `${md(r.data.label)} · ${md(r.data.url ?? (r.content?.verified ? "local artifact; digest verified" : "local artifact; content not verified"))}`).join("\n") || "No artifacts recorded."}\n\n**Latest decisions**\n${task.decisions.map(r => `${md(r.at)} · ${md(r.decision)} · ${md(r.why)}`).join("\n") || "No decisions recorded."}`;
}
export function renderBoardText(model) {
  return `**sage board** · ${md(model.at)}\n🔴 ${model.counts.needsOwner} need you · ${model.counts.recordedAgents} recorded agents · ${model.counts.inferredWork} inferred PRs · 🔁 ${model.counts.inReview} in review\n\n### 🔴 Needs you\n${model.needsOwner.map((task, i) => `**${i + 1} · ${md(task.id)} ${md(task.title)}**\n${md(task.sourceLabel)} · ${md(task.projectName)}\n${task.reasons.map(reason => `> ${reason.gateId ? `${md(reason.key)} · ` : ""}${md(reason.text)}${reason.options?.length ? `\n> Options: ${reason.options.map((option, i) => `${i + 1}: ${md(option)}`).join(" · ")}` : ""}${reason.recommendation ? `\n> Recommended: ${md(reason.recommendation)}` : ""}`).join("\n")}`).join("\n\n") || "No recorded task needs you."}\n\n${model.columns.map(column => `### ${columnMark(column.key)} ${md(column.name)}\n${column.tasks.map(task => `**${md(task.id)} ${md(task.title)}** · ${md(task.sourceLabel)} · ${md(task.projectName)}${task.pr ? ` · PR ${md(task.pr)}` : ""}\n${task.agents.map(agent => `${md(agent.provider ?? "provider unknown")} · ${md(agent.role)} · recorded running`).join("\n")}\n${task.inferredWork ? "Inferred from the open PR.\n" : ""}${task.cycles.map(c => `Cycle ${c.number} of ${task.requiredCycles}: ${c.steps.map(s => `${mark(s.status)} ${s.role}`).join(" · ")}`).join("\n")}`).join("\n\n") || "No tasks."}`).join("\n\n")}\n${model.diagnostics.map(d => `Incomplete source: ${md(d.source)} · ${md(d.message)}`).join("\n")}`;
}
export function renderBoardStatus(model) {
  const states = new Map(); for (const task of model.tasks) states.set(task.state, (states.get(task.state) ?? 0) + 1);
  return `Tasks: ${[...states].map(([state,n]) => `${state} ${n}`).join(" · ") || "none recorded"}\nAgents: ${model.counts.recordedAgents} recorded running · ${model.counts.inferredWork} inferred PRs\nOwner: ${model.counts.needsOwner} tasks need you\nBudget this week: unknown; no provider observation available${model.diagnostics.length ? `\nSources: ${model.diagnostics.length} diagnostics; counts may be incomplete` : ""}`;
}
