import { rewriteCoreImports } from "./package-imports.mjs";
// Builds the generated files from the sources, so each principle has one copy:
//   principles/*.md, writing/ste-80.md, writing/readme.md, preferences/working-preferences.md  (the sources)
//   upstream/pstack/skills/principle-*/SKILL.md  (pstack, kept up to date by scripts/sync-pstack.mjs)
//   → plugins/sage/skills/<name>/SKILL.md   (one skill per principle, plus the writing standard and the README guide)
// A principle in principles/ overrides pstack's principle of the same id. pstack's other principles go in as they are.
//   → instructions/core.md                        (the always-on file: preferences + writing standard)
//   writing/dictionary.md → plugins/sage/skills/dictionary/SKILL.md, and the word table in README.md (scripts/dictionary.mjs)
// Run `npm run build` after editing a source; `npm run check` fails when a generated file is out of date.
import { mkdirSync, readFileSync, readdirSync, rmSync, rmdirSync, renameSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSync } from "esbuild";
import { renderRoleInstructions, renderReportInstructions, renderChiefInstructions } from "../packages/sage-core/index.mjs";
import { checkWords, withWordTable, wordTable } from "./dictionary.mjs";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS = join(ROOT, "packages/sage-claude/skills");
export const GENERATED = "<!-- Generated by scripts/build.mjs from the sources; edit the source, then run npm run build. -->";

/** A source file: YAML-like frontmatter of `key: value` lines, then the body. */
export function parseSource(text, file) {
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
  if (!m) throw new Error(`${file}: no frontmatter`);
  const meta = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i < 1) throw new Error(`${file}: bad frontmatter line "${line}"`);
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: m[2].trim() };
}

const q = (s) => JSON.stringify(s); // YAML accepts JSON strings
const skill = (name, description, source, body) =>
  `---\nname: ${name}\ndescription: ${q(description)}\nlicense: MIT\nmetadata:\n  source: ${q(source)}\n---\n\n${GENERATED}\n\n${body}\n`;

/** pstack's principles that no file in principles/ overrides, from upstream/pstack at the pinned commit. */
function upstreamPrinciples(own) {
  const base = join(ROOT, "upstream/pstack/skills");
  const { sha } = JSON.parse(readFileSync(join(ROOT, "upstream/pstack.json"), "utf8"));
  if (!existsSync(base)) return [];
  return readdirSync(base)
    .filter((d) => d.startsWith("principle-") && !own.has(d.slice("principle-".length)))
    .sort()
    .map((d) => {
      const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(readFileSync(join(base, d, "SKILL.md"), "utf8"));
      const desc = /^description:\s*(.+)$/m.exec(m[1])[1].trim();
      const body = m[2].trim();
      const title = /^#\s+(.+)$/m.exec(body)[1].trim();
      return { name: d, title, description: desc.startsWith('"') ? JSON.parse(desc) : desc, body, source: `pstack ${d}, MIT, Copyright (c) 2026 Lauren Tan, github.com/cursor/plugins at ${sha.slice(0, 7)}, as it is` };
    });
}

/** A link to another skill stays only when that skill ships: [text](../<skill>/SKILL.md) becomes text otherwise. */
const keepLinks = (body, ships) => body.replace(/\[([^\]]+)\]\(\.\.\/([a-z0-9-]+)\/SKILL\.md\)/g, (all, text, target) => (ships.has(target) ? all : text));

export function outputs() {
  const out = new Map();
  const principles = readdirSync(join(ROOT, "principles")).filter((f) => f.endsWith(".md") && f !== "README.md").sort();
  const own = new Set();
  for (const f of principles) {
    const { meta, body } = parseSource(readFileSync(join(ROOT, "principles", f), "utf8"), f);
    const name = `principle-${meta.id}`;
    own.add(meta.id);
    out.set(join("plugins/sage/skills", name, "SKILL.md"), skill(name, `${meta.name}. Apply when ${meta.applyWhen}`, meta.source, `# ${meta.name}\n\n${body}`));
  }
  const upstream = upstreamPrinciples(own);
  const ships = new Set([...readdirSync(SKILLS), ...[...own].map((id) => `principle-${id}`), ...upstream.map((u) => u.name)]);
  for (const u of upstream) out.set(join("plugins/sage/skills", u.name, "SKILL.md"), skill(u.name, `${u.title}. ${u.description}`, u.source, keepLinks(u.body, ships)));
  const w = parseSource(readFileSync(join(ROOT, "writing/ste-80.md"), "utf8"), "writing/ste-80.md");
  out.set("plugins/sage/skills/writing-standard/SKILL.md", skill("writing-standard", `${w.meta.name}. Apply to ${w.meta.applyWhen}`, w.meta.source, `# ${w.meta.name}\n\n${w.body}`));
  const r = parseSource(readFileSync(join(ROOT, "writing/readme.md"), "utf8"), "writing/readme.md");
  out.set("plugins/sage/skills/readme-guide/SKILL.md", skill("readme-guide", `${r.meta.name}. Apply when ${r.meta.applyWhen}`, r.meta.source, `# ${r.meta.name}\n\n${r.body}`));
  const d = parseSource(readFileSync(join(ROOT, "writing/dictionary.md"), "utf8"), "writing/dictionary.md");
  checkWords(d.body); // a dictionary that the check cannot use stops the build
  out.set("plugins/sage/skills/dictionary/SKILL.md", skill("dictionary", `${d.meta.name}: sage's approved words, one meaning each, and the words not to say. Apply to ${d.meta.applyWhen}`, d.meta.source, `# ${d.meta.name}\n\n${d.body}`));
  out.set("README.md", withWordTable(readFileSync(join(ROOT, "README.md"), "utf8"), wordTable(d.body)));
  const p = parseSource(readFileSync(join(ROOT, "preferences/working-preferences.md"), "utf8"), "preferences/working-preferences.md");
  out.set("instructions/core.md", `${GENERATED}\n\n# ${p.meta.name}\n\n${p.body}\n\n# ${w.meta.name}\n\n${w.body}\n`);
  return packageOutputs(out);
}

/** Files below one directory, in a stable order. No link can escape a package. */
export function filesUnder(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`package contains a symbolic link: ${path}`);
    return entry.isDirectory() ? filesUnder(path) : [path];
  });
}

function packageOutputs(generated) {
  const out = new Map([...generated].filter(([path]) => !path.startsWith("plugins/")));
  const core = JSON.parse(readFileSync(join(ROOT, "packages/sage-core/package.json"), "utf8"));
  const sharedSkills = [...generated].filter(([path]) => path.startsWith("plugins/sage/skills/"));
  for (const [provider, target] of [["claude", "plugins/sage"], ["codex", "plugins/sage-codex"]]) {
    const source = join(ROOT, `packages/sage-${provider}`);
    const meta = JSON.parse(readFileSync(join(source, "package.json"), "utf8"));
    if (meta.dependencies?.[core.name] !== core.version) throw new Error(`${meta.name} must pin ${core.name} ${core.version}`);
    for (const file of filesUnder(source)) {
      const rel = relative(source, file);
      if (rel === "package.json") continue;
      // Resolve the one public dependency at build time; installed plugins need no npm install.
      const specifier = relative(dirname(rel), "core/index.mjs").replaceAll("\\", "/");
      let text = readFileSync(file, "utf8");
      if (text.includes("<!-- sage-core-chief -->")) {
        const bindings = JSON.parse(readFileSync(join(source, "chief-bindings.json"), "utf8"));
        text = text.replaceAll("<!-- sage-core-chief -->", renderChiefInstructions(bindings));
      }
      if (/<!-- sage-core-(?:role: |report)/.test(text)) {
        const bindings = JSON.parse(readFileSync(join(source, "role-bindings.json"), "utf8"));
        text = text.replace(/<!-- sage-core-role: ([a-z-]+) -->/g, (_, role) => renderRoleInstructions(role, { ...bindings.common, ...bindings[role] }))
          .replace(/<!-- sage-core-report -->/g, () => renderReportInstructions(bindings.report));
      }
      if (provider === "codex" && rel === "runtime/mcp-sdk.mjs") {
        const result = buildSync({
          absWorkingDir: ROOT, entryPoints: [relative(ROOT, file)], bundle: true,
          platform: "node", target: "node20", format: "esm", write: false,
          minify: true, legalComments: "eof", logLevel: "silent",
        });
        out.set(join(target, rel), result.outputFiles[0].text);
        continue;
      }
      const content = rel.endsWith(".mjs") ? rewriteCoreImports(text, specifier.startsWith(".") ? specifier : `./${specifier}`) : text;
      out.set(join(target, rel), content);
    }
    for (const file of filesUnder(join(ROOT, "packages/sage-core"))) {
      const rel = relative(join(ROOT, "packages/sage-core"), file);
      out.set(join(target, "core", rel), readFileSync(file, "utf8"));
    }
    for (const [path, text] of sharedSkills) out.set(path.replace("plugins/sage", target), text);
    if (provider === "codex") {
      const dependencies = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).devDependencies;
      // The SDK also embeds these libraries in its published JavaScript.
      for (const name of ["@modelcontextprotocol/server", "@modelcontextprotocol/core", "zod",
        "ajv", "ajv-formats", "fast-deep-equal", "fast-uri", "json-schema-traverse", "content-type"]) {
        const dir = join(ROOT, "node_modules", name);
        const installed = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
        const expected = dependencies[name === "@modelcontextprotocol/core" ? "@modelcontextprotocol/server" : name];
        if (installed.version !== expected) throw new Error(`${name} must match the pinned build dependency`);
        out.set(join(target, "licenses", `${name.replaceAll("/", "-")}.txt`),
          `${name} ${installed.version}\n\n${readFileSync(join(dir, "LICENSE"), "utf8")}`);
      }
    }
    out.set(join(target, "LICENSE"), readFileSync(join(ROOT, "LICENSE"), "utf8"));
    out.set(join(target, "LICENSE-pstack"), readFileSync(join(ROOT, "upstream/pstack/LICENSE"), "utf8"));
    out.set(join(target, "build.json"), JSON.stringify({ package: meta.name, version: meta.version, core: core.version }, null, 2) + "\n");
  }
  return out;
}

function removeEmptyDirectories(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) if (entry.isDirectory()) removeEmptyDirectories(join(dir, entry.name));
  if (!readdirSync(dir).length) rmdirSync(dir);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  let built;
  try { built = outputs(); } catch (e) { console.error(`✗ ${e.message}`); process.exit(1); }
  for (const [rel, text] of built) {
    const file = join(ROOT, rel);
    if (existsSync(file) && readFileSync(file, "utf8") === text) continue;
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(`${file}.build`, text);
    renameSync(`${file}.build`, file);
  }
  // Delete files absent from the recipe without tearing down the whole plugin tree.
  for (const dir of ["plugins/sage", "plugins/sage-codex"]) {
    for (const file of filesUnder(join(ROOT, dir))) if (!built.has(relative(ROOT, file))) rmSync(file);
    removeEmptyDirectories(join(ROOT, dir));
  }
  console.log(`built ${built.size} files`);
}
