// Builds the generated files from the sources, so each principle has one copy:
//   principles/*.md, writing/ste-80.md, preferences/working-preferences.md  (the sources)
//   → plugins/sage/skills/<name>/SKILL.md   (one skill per principle, plus the writing standard)
//   → instructions/core.md                        (the always-on file: preferences + writing standard)
// Run `npm run build` after editing a source; `npm run check` fails when a generated file is out of date.
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS = join(ROOT, "plugins/sage/skills");
const GENERATED = "<!-- Generated by scripts/build.mjs from the sources; edit the source, then run npm run build. -->";

/** A source file: YAML-like frontmatter of `key: value` lines, then the body. */
export function parseSource(text, file) {
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(text);
  if (!m) throw new Error(`${file}: no frontmatter`);
  const meta = {};
  for (const line of m[1].split("\n")) {
    const i = line.indexOf(":");
    if (i < 1) throw new Error(`${file}: bad frontmatter line "${line}"`);
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: m[2].trim() };
}

const q = (s) => JSON.stringify(s); // YAML accepts JSON strings
const skill = (name, description, source, body) =>
  `---\nname: ${name}\ndescription: ${q(description)}\nlicense: MIT\nmetadata:\n  source: ${q(source)}\n---\n\n${GENERATED}\n\n${body}\n`;

export function outputs() {
  const out = new Map();
  const principles = readdirSync(join(ROOT, "principles")).filter((f) => f.endsWith(".md") && f !== "README.md").sort();
  for (const f of principles) {
    const { meta, body } = parseSource(readFileSync(join(ROOT, "principles", f), "utf8"), f);
    const name = `principle-${meta.id}`;
    out.set(join("plugins/sage/skills", name, "SKILL.md"), skill(name, `${meta.name}. Apply when ${meta.applyWhen}`, meta.source, `# ${meta.name}\n\n${body}`));
  }
  const w = parseSource(readFileSync(join(ROOT, "writing/ste-80.md"), "utf8"), "writing/ste-80.md");
  out.set("plugins/sage/skills/writing-standard/SKILL.md", skill("writing-standard", `${w.meta.name}. Apply to ${w.meta.applyWhen}`, w.meta.source, `# ${w.meta.name}\n\n${w.body}`));
  const p = parseSource(readFileSync(join(ROOT, "preferences/working-preferences.md"), "utf8"), "preferences/working-preferences.md");
  out.set("instructions/core.md", `${GENERATED}\n\n# ${p.meta.name}\n\n${p.body}\n\n# ${w.meta.name}\n\n${w.body}\n`);
  return out;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  // Remove generated skill folders that no longer have a source (own skills, without the marker, are kept).
  if (existsSync(SKILLS)) for (const d of readdirSync(SKILLS)) {
    const f = join(SKILLS, d, "SKILL.md");
    if (existsSync(f) && readFileSync(f, "utf8").includes(GENERATED)) rmSync(join(SKILLS, d), { recursive: true });
  }
  for (const [rel, text] of outputs()) {
    mkdirSync(dirname(join(ROOT, rel)), { recursive: true });
    writeFileSync(join(ROOT, rel), text);
  }
  console.log(`built ${outputs().size} files`);
}
